### ISSUE TITLE
Updated version release

### ISSUE THREAD

**Issue by sheinbergon** [davidmc24/gradle-avro-plugin#100]
Hi David.

First, let me thank you for your work on this project.
Second, it seems the latest version (0.17) does not contain the `createOptionalGetters` feature.
Is there anywhere I can find snapshot builds? Is there a plan to release an update version any time soon?

10x

**Comment by davidmc24** [comment]
Thanks for asking.  I had been holding off on releasing because I thought I was going to have time to get more done to include in the release... but it looks like I didn't.  So, new release today!  Will close this ticket once the release is ready.

**Comment by davidmc24** [comment]
Version 0.18.0 released
