### ISSUE TITLE
Schema dependency not recognized

### ISSUE THREAD

**Issue by dejank1986** [davidmc24/gradle-avro-plugin#103]
I have externalized complex type in separate schema file as suggested. Plugin docs says "The plugin will automatically recognize the dependency and compile the files in the correct order", but that was not the case. Build fails because it does not recognize complex type. However if I first run build with only file that holds definition of complex type, and I add that complex type to parent schema after and run build again, everything works fine, so it really looks like schemas are not compiled in proper order.

Is there any additional config that I am missing?

**Environment:**
 - Gradle Version: 6.0.1
 - Apache Avro Version: 1.9.1
 - Gradle-Avro Plugin Version: 0.9.1
 - OS: Mac OS Catalina

**Comment by davidmc24** [comment]
Do you have a reproducible example project you can share?

While it likely isn't the cause of your problem, plugin version 0.9.1 is a couple years old (there are more recent versions available), and I haven't updated the plugin to support Gradle 6.x quite yet.

**Comment by dejank1986** [comment]
Complex type schema:
```
{
    "name": "Source",
    "namespace": "com.example",
    "type": "enum",
    "symbols" : ["source1", "source2", "source3"]
}
```

Parent schema:
``
{
  "type": "record",
  "name": "Listing",
  "namespace": "com.example",
  "fields": [
    {
      "name": "source",
      "type": "Source"
    }
  ]
}
```

Nothing specific in build.gradle, I have just included plugin. Also both schemas are in src/main/avro

**Comment by davidmc24** [comment]
I put those schema files in my test project in `src/main/avro` as `Source.avsc` and `Listing.avsc`, ran `./gradlew clean build`, and saw that `build/classes/java/main/com/example/` contained `Source.class` and `Listing.class`.  It looks to be working for me.

**Comment by dejank1986** [comment]
Can you please share your test project so I can compare is there anything different?

**Comment by davidmc24** [comment]
[gradle-avro-plugin-test.zip](https://github.com/davidmc24/gradle-avro-plugin/files/4237630/gradle-avro-plugin-test.zip)

**Comment by davidmc24** [comment]
Closed due to lack of further responses from requestor.  Feel free to re-open if desired.
