### ISSUE TITLE
Unable to generate JODA DateTime type

### ISSUE THREAD

**Issue by FranckyBoyX** [davidmc24/gradle-avro-plugin#109]
**Prerequisites**

* [ ] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [ ] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [ ] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [ ] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [ ] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

Unable to generate JODA DateTime type from timestamp-millis logical type.

**To Reproduce**

Schema configuration
      {
         "name":"date",
         "type":"long",
         "logicalType":"timestamp-millis"
      }

plugin configuration

avro {
    createSetters = false
    dateTimeLogicalType = 'JODA'
}

**Expected behavior**

I expected the generated `date` field to be of Joda.DateTime type but instead got a `Long`

**Environment (please complete the following information):**

 - Gradle Version [e.g. 5.1.1]
 - Apache Avro Version [e.g. 1.9.2]
 - Gradle-Avro Plugin Version [e.g. 0.19.1]
 - Java Version [e.g. 8]
 - OS: [e.g. Mac OS X Mojave]

**Comment by FranckyBoyX** [comment]
Hi there! Not sure this is really a bug or a misconfiguration on my part. Thanks for helping me clarify

**Comment by davidmc24** [comment]
Happy to help.  Let's start by trying to figure out if this schema is supported by Avro in general, without involving gradle-avro-plugin.

Steps:

* Download avro-tools-1.9.2.jar from [Apache Avro Releases](https://avro.apache.org/releases.html)
* Store your schema as a file (I called it `Test.avsc`)
* Run the schema compilation: `java -jar avro-tools-1.9.2.jar compile -dateTimeLogicalTypeImpl joda schema Test.avsc .`
  * Based on directions in [Apache Avro Getting Started](https://avro.apache.org/docs/current/gettingstartedjava.html)
* Check the output (in my case, `Test.java`)

The schema you provided doesn't appear to be a valid type by itself, but rather a field snippet, so the test file I used was:

```
{"type": "record",
 "name": "Test",
 "fields": [
     {"name": "name", "type": "string"},
     {
     "name":"date",
     "type":"long",
     "logicalType":"timestamp-millis"
     }
 ]
}
```

It appears to me that this schema has the behavior that you noticed; it will be represented as a Long.

[AVRO-2123](https://issues.apache.org/jira/browse/AVRO-2123) appears to include an example of the expected schema for using `logicalType`.

This file appears to have a better behavior (`Test2.avsc`):

```
{"type": "record",
 "name": "Test2",
 "fields": [
     {
     "name":"date",
     "type":{ "type" : "long", "logicalType" : "timestamp-millis" }
    }
 ]
}
```

Note that the field's type is now an object containing both a `type` and `logicalType`.

**Comment by FranckyBoyX** [comment]
Wow thanks for the quick answer. The proposed fix works perfectly!

**Comment by DANIELK121** [comment]
@FranckyBoyX @davidmc24 
Is this configuration
```
avro {
dateTimeLogicalType = 'JODA'
}
```
also available with MAVEN somehow?

I've tried different things and couldn't get it to work...

Environment:
Maven Version [e.g. 3.8.4]
Apache Avro Version [e.g. 1.11.3]
avro-maven-plugin Version [e.g. 1.11.0]
Java Version [e.g. 11]
