### ISSUE TITLE
UUID Logical Type generating java.lang.String

### ISSUE THREAD

**Issue by hitchan** [davidmc24/gradle-avro-plugin#110]
Apologies if i'm doing something wrong here, but from what I can tell my configuration is correct.

I have a simple avro definition with a UUID logical type as follows.

    {
      "name": "id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    }

The generated class is still using a java.lang.String type though. Am I missing something here? I would expect this to be of type java.util.UUID.

**Comment by davidmc24** [comment]
The schema looks valid to me, as per the [Avro specification](https://avro.apache.org/docs/current/spec.html).  However, it doesn't appear to "work" (as in result in a `UUID` being used) when using the [avro-tools `compile schema` command](https://avro.apache.org/docs/current/gettingstartedjava.html#Compiling+the+schema).  I recommend requesting support from the [Apache Avro project](https://avro.apache.org/).

**Comment by hitchan** [comment]
Thanks for the quick reply, I will do that!

**Comment by paslavsky** [comment]
Just for history. 
I solved this issue by adding custom conversion like:
```
avro {
    customConversion(Conversions.UUIDConversion.class)
}
```

**Comment by devinrsmith** [comment]
Is this merged PR relevant? https://github.com/apache/avro/pull/1362

**Comment by davidmc24** [comment]
It might mean that if the plugin is using a version that includes that PR, it wouldn't be needed to resister the UUID conversion.
