### ISSUE TITLE
LogicalType in avsc schema is not supported by plugin

### ISSUE THREAD

**Issue by SaikiranBoppudi** [davidmc24/gradle-avro-plugin#113]
Hi ,

I do have a schema with logicalType date as below. But the AvroGenerated class still shows the data type as **int** not as **date** : 

{
  "type" : "record",
  "name" : "JourneyData",
  "namespace" : "com.journey.avro.schema",
  "fields" : [ {
    "name" : "journeyId",
    "type" : "int"
  }, {
    "name" : "route",
    "type" : "string"
  }, {
    "name" : "startDate",
    "type" : "int",
    "logicalType" : "date"
  }, {
    "name" : "endDate",
    "type" : "int",
    "logicalType" : "date"
  }
  ]
}

Please post if there is any approach to do this from avsc to Class generation

**Comment by davidmc24** [comment]
The provided schema doesn't do what you want.  To apply a logical type, it needs to look like this:

```
{
  "type": "record",
  "name": "JourneyData",
  "namespace": "com.journey.avro.schema",
  "fields": [
    {
      "name": "journeyId",
      "type": "int"
    },
    {
      "name": "route",
      "type": "string"
    },
    {
      "name": "startDate",
      "type": {
        "type": "int",
        "logicalType": "date"
      }
    },
    {
      "name": "endDate",
      "type": {
        "type": "int",
        "logicalType": "date"
      }
    }
  ]
}
```

**Comment by SaikiranBoppudi** [comment]
Thanks @davidmc24
