### ISSUE TITLE
kafka-topic with timestamp-millis in schema appending 000 to timestamp

### ISSUE THREAD

**Issue by SaikiranBoppudi** [davidmc24/gradle-avro-plugin#114]
Hi,

I have a topic with schema field date as
{
  "name": "endDate",
  "type": {
    "type": "long",
    "logicalType": "timestamp-millis"
  }
}

However when I read the message from kafka I can see 000 are appended to milliseconds in timestamp. 
endDate in Kafka : 1591597943512
endDate after consuming :  1591597943512000.

Please suggest a solution

**Comment by davidmc24** [comment]
I'm sorry you're having a problem, but this doesn't sound related to any behaviors that this plugin controls.  I think that you're more likely to get assistance on the Apache Avro User's Mailing List: https://avro.apache.org/mailing_lists.html#Users
