### ISSUE TITLE
Usage Question - Is there a gradle task to generate the avsc files that have exterenal references?

### ISSUE THREAD

**Issue by ykcai** [davidmc24/gradle-avro-plugin#115]
Basically I have several avsc files, 1 main and the rest are embedded and reference via the namespace.
Is there a way to generate the final file that has all the embedded avsc? I am doing this so that my confluent schema registry can be updated with this **complete** avro.

I can see that the generated Java class has the correct resulting Avro schema but is there a way for me to get that as a file? I can see some work on this with the `CompileAvroFromSchemaTask`

**Comment by davidmc24** [comment]
This task does not yet exist.  It's on my todo list.  I'd been hoping to add it as part of the next major version, which would break the execution of Avro out from the plugin classpath, allowing for support for arbitrary versions of Avro without changing the version of the plugin, but time to work on that sort of change is elusive at best.  Just pulling the resolution logic into a standalone task shouldn't take long.  I'll try to get to it in the next week.  Feel free to ping me again on this ticket if you don't hear back by 2020-06-19.

**Comment by davidmc24** [comment]
New task included in version 0.20.0; documented in README.
