### ISSUE TITLE
Javadoc generation fails with tag-like doc field

### ISSUE THREAD

**Issue by izeye** [davidmc24/gradle-avro-plugin#116]
**Prerequisites**

* [x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [x] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

If `doc` field includes a tag-like value such as "\<first name\>", Javadoc generation fails.

**To Reproduce**

1. Sample project: https://github.com/izeye/samples-java-branches/tree/avro
2. Sample schema file:

```
{
  "namespace": "learningtest.avro",
  "type": "record",
  "name": "User",
  "doc": "User.",
  "fields": [
    {
      "name": "name",
      "type": "string",
      "doc": "Name. <first name> <last name>"
    },
    {
      "name": "favorite_number",
      "type": [
        "int",
        "null"
      ],
      "doc": "Favorite number."
    },
    {
      "name": "favorite_color",
      "type": [
        "string",
        "null"
      ],
      "doc": "Favorite color."
    }
  ]
}
```

3. Run the following command:

```
./gradlew clean javadoc
```

4. Errors:

```
> Task :javadoc FAILED
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:75: error: unknown tag: first
  /** Name. <first name> <last name> */
            ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:75: error: unknown tag: last
  /** Name. <first name> <last name> */
                         ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:91: error: unknown tag: first
   * @param name Name. <first name> <last name>
                       ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:91: error: unknown tag: last
   * @param name Name. <first name> <last name>
                                    ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:126: error: unknown tag: first
   * @return Name. <first name> <last name>
                   ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:126: error: unknown tag: last
   * @return Name. <first name> <last name>
                                ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:135: error: unknown tag: first
   * Name. <first name> <last name>
           ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:135: error: unknown tag: last
   * Name. <first name> <last name>
                        ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:273: error: unknown tag: first
      * Name. <first name> <last name>
              ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:273: error: unknown tag: last
      * Name. <first name> <last name>
                           ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:283: error: unknown tag: first
      * Name. <first name> <last name>
              ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:283: error: unknown tag: last
      * Name. <first name> <last name>
                           ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:296: error: unknown tag: first
      * Name. <first name> <last name>
              ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:296: error: unknown tag: last
      * Name. <first name> <last name>
                           ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:306: error: unknown tag: first
      * Name. <first name> <last name>
              ^
/Users/user/IdeaProjects/samples-java-branches/build/generated-main-avro-java/learningtest/avro/User.java:306: error: unknown tag: last
      * Name. <first name> <last name>
                           ^
16 errors
```

**Expected behavior**

Escape `doc` fields to be rendered properly for Javadoc.

**Environment (please complete the following information):**
 - Gradle Version: 6.5
 - Apache Avro Version: 1.9.2
 - Gradle-Avro Plugin Version: 0.20.0
 - Java Version: 11.0.6
 - OS: macOS High Sierra

**Additional context**

N/A

**Comment by davidmc24** [comment]
I'm sorry you're having problems, but this isn't a problem with this project (gradle-avro-plugin).  If you want this behavior changed, please submit a ticket with the Apache Avro project.

As demonstrated below, this behavior is manifested when using the command-line Avro compiler:

1. Store the provided schema as `User.avsc`
2. Download `avro-1.9.2.jar` and `avro-tools-1.9.2.jar` from https://avro.apache.org/releases.html#Download
3. Run `java -jar avro-tools-1.9.2.jar compile schema User.avsc out`
4. Check the output in `out/learningtest/avro/User.java`
5. Run `javadoc -classpath avro-1.9.2.jar out/learningtest/avro/User.java` and see that it produces errors.

In your case, you can fix the errors by escaping the unintended HTML tags in the docstring.  The updated line in your schema file would look like this:

`"doc": "Name. &lt;first name&gt; &lt;last name&gt;"`

If you want such escaping to happen automatically, it should be done by the compiler produced by the Apache Avro project.

**Comment by izeye** [comment]
@davidmc24 Thanks for the quick feedback!

I created https://issues.apache.org/jira/browse/AVRO-2869.
