### ISSUE TITLE
Usage question: possibility to check which fields have defined default values

### ISSUE THREAD

**Issue by ismarslomic** [davidmc24/gradle-avro-plugin#117]
I would like to find out which fields in generated Java objects has defined default value in Avro schema definition and not. Is it possible to access this in some way programmatically?

**Comment by davidmc24** [comment]
Should be possible.  The generated classes have a `getSchema()` method, which provides access to the Schema object from the Avro Java API.  From there you should be able to enumerate the fields and check their defaults.

For further questions about the generated Java objects or the Avro Java API, please direct them to the Apache Avro project (https://avro.apache.org/)  as it doesn't really have anything to do with this plugin.

https://avro.apache.org/docs/current/api/java/org/apache/avro/Schema.html#getFields--
https://avro.apache.org/docs/current/api/java/org/apache/avro/Schema.Field.html#defaultVal--
