### ISSUE TITLE
'conversions' array is not populated for Avro Union Logicaltype fields

### ISSUE THREAD

**Issue by pdebuitlear** [davidmc24/gradle-avro-plugin#120]
**Prerequisites**

* [X] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [X] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [X] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [X] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [X] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

=====================

I think I am reproducing the same issue as the one described [here](https://stackoverflow.com/questions/45581437/how-to-specify-converter-for-default-value-in-avro-union-logical-type-fields).

1. Configure the plugin with the following parameter:
```dateTimeLogicalType = 'JSR310'```

2. Invoke the plugin with the following avsc:
```	{
	  "type": "record",
	  "name": "Messages",
	  "namespace": "com.somedomain",
	  "fields": [
		{
		  "name": "start",
		  "type": {
			"type": "long",
			"logicalType": "timestamp-millis"
		  }
		},
		{
		  "name": "end",
		  "type": [
			"null",
			{
			  "type": "long",
			  "logicalType": "timestamp-millis"
			}
		  ],
		  "default": null
		}
	  ]
	}
```

**Expected behavior**

<pre>
  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      <b>new org.apache.avro.data.TimeConversions.TimestampMillisConversion()</b>,
      null
  };
</pre>

**Actual behavior**

```
  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };
```

**Environment (please complete the following information):**
 - Gradle Version [6.3]
 - Apache Avro Version [1.9.2]
 - Gradle-Avro Plugin Version [0.20.0]
 - Java Version [11]
 - OS: [Windows 10]

**Comment by davidmc24** [comment]
I'm sorry you're having difficulties.  A bit of good news and bad news here.

Good news: I was able to reproduce your problem ([see RecordTest](https://github.com/davidmc24/gradle-avro-plugin/blob/master/test-project/src/test/java/project/RecordTest.java)).

Bad news: it looks to me like this is an Avro bug (not anything under control of the Gradle plugin), and despite it claiming it was fixed under [AVRO-2065](https://issues.apache.org/jira/browse/AVRO-2065), it still looks broken to me.  In [CLIComparisonTest](https://github.com/davidmc24/gradle-avro-plugin/blob/master/test-project/src/test/java/project/CLIComparisonTest.java) I verified that for your schema, the Gradle plugin produces exactly the same Java source file as the Apache Avro CLI tool's "compile schema" command.

Please follow up with the [Apache Avro project](https://avro.apache.org/).
