### ISSUE TITLE
Option to not generate the builder method

### ISSUE THREAD

**Issue by dxxvi** [davidmc24/gradle-avro-plugin#121]
This was mentioned [a few years ago](https://github.com/davidmc24/gradle-avro-plugin/issues/38) and I'm not sure if there's any solution yet.

Avro has an [option](https://github.com/apache/avro/pull/192/files) (line 98). Is it possible to do that in this gradle plugin?

Thanks.

**Comment by davidmc24** [comment]
@dxxvi 

This is not a true "option" in the Avro `SpecificCompiler`, as there is no provided way of setting it.  Rather, `SpecificCompiler` determines automatically whether it will generate the all-args constructor as part of the schema compilation process.  As it is not currently something that can be passed in/configured, it isn't currently to control it in this Gradle plugin.

If the Avro project adds a way to configure such a setting, I would be happy to support it in this plugin.
