### ISSUE TITLE
Update version reference on gradle.org

### ISSUE THREAD

**Issue by s-thoeni** [davidmc24/gradle-avro-plugin#122]
Hi, 

Not a bug per se but i found about gradle-avro-plugin via gradle.org (https://plugins.gradle.org/plugin/com.commercehub.gradle.plugin.avro). The plugin version referenced as latest is still 0.9.1. Me and i am sure others have had compatibility issues initially because of this. 

Thanks for the awesome plugin. 

Edit: i just saw that the publication on gradle.org is still in discussion with #91. I do think publishing there is useful.

**Comment by davidmc24** [comment]
At one point I had put a notice in the description in the Gradle plugin portal that new versions were no longer being posted there. It appears to have been lost.

Since people continue to discover the plugin from there despite no updates on the portal in 3 years, it may be worth considering further action.

I'm not going to resume publishing to the portal unless they make download stats easily available to plugin authors, so that's not an option right now. 

I had already tried a notice and that doesn't seem to be effective, as it appears to have been lost and even when it was up people often miss it.

The remaining options are either to delete the plugin from the plugin portal entirely (in which case people who are searching there directly will likely go with a different plugin) or upload a version of the plugin that notifies that you're using a badly out of date version of the plugin and directs you to the appropriate site.

**Comment by davidmc24** [comment]
If pursuing a redirector, it could either be functional (at least as functional as the 0.9.1 version currently published there) and provide only warning messages, or provide no actual function and cause a build failure when included.  I wouldn't remove 0.9.1 at this time, as I don't want to break any existing builds referencing it without notice. There's potential for a hybrid; have a redirector version that "works" but gives informational warnings, and in the warnings includes a cut-off date after which it will stop functioning and only result in errors. After a newer version has been available for a while, I think I could be comfortable with deleting the previous versions.

**Comment by davidmc24** [comment]
If I were to pursue this, here's my current beat proposal:

* Upload a new version to the plugin portal, 0.9.2 (chosen to be higher than the latest version on the plugin portal, but not conflict with any versions published elsewhere)
* In that version, it will have the same behavior as 0.9.1, except the differences below
* Until the cutoff date, it will log at warning level on every run with a message such as "This version of gradle-avro-plugin is obsolete and will stop working on CUTOFF-DATE.  Please upgrade to a newer version from https://github.com/davidmc24/gradle-avro-plugin at your earliest opportunity."
* On the cutoff date, it will stop working and will throw an error on every run, with a message such as "This version of gradle-avro-plugin is obsolete and will no longer function. It will be deleted from the Gradle Plugin Portal on DELETE-DATE.  Please upgrade to a newer version from https://github.com/davidmc24/gradle-avro-plugin at your earliest opportunity."
* The cut-off date would be 18 months from the publishing of the new version.
* The delete date would be 12 months after the cut-off date.

I'm comfortable with breaking builds that either are using 0.9.1 and don't upgrade at all in 2.5 years, or upgrade to 0.9.2 but don't pay attention to the warnings.

**Comment by davidmc24** [comment]
Until/unless download stats are provided by the Gradle Plugin Portal, I will definitely **not** be publishing new versions of this plugin to the Gradle Plugin portal.  If you're interested in using the Gradle Plugin Portal, I suggest that you encourage Gradle to work on https://github.com/gradle/plugin-portal-requests/issues/2 (which I first requested back in 2015 under https://discuss.gradle.org/t/plugin-portal-download-statistics/11609).

**Comment by s-thoeni** [comment]
Hi, thanks alot for you thorough explanation. I understand your concern.

It seems the people from the Gradle Plugin Portal are working on a solution for providing download statistics. Until then im absolutely fine with the status quo

**Comment by davidmc24** [comment]
@s-thoeni Thank you for understanding.  It does seem like Gradle may be making some progress on download statistics.  If they release such a capability, I would be happy to start publishing there again.

**Comment by davidmc24** [comment]
Working on the warning plugin version to publish to the gradle plugin portal

**Comment by davidmc24** [comment]
Version 0.99.99 has been published to the Gradle Plugin Portal.

In the description, it calls out that versions published to the Gradle Plugin Portal are obsolete and points to the project site for up-to-date versions.

The version is equivalent in functionality to the previous version published there (0.9.1) with the exception that it will disable itself on 2022-08-10, and outputs a warning message every build until then.

As Gradle indicates that "Keep in mind that plugins being used by builds will not be able to be deleted.", it may not be possible to de-list the plugins after an additional 12 months as I had originally intended, but at least with the updated messaging it seems likely that more people will discover up-to-date versions.
