### ISSUE TITLE
AVPR Output Directory Files

### ISSUE THREAD

**Issue by mhandria** [davidmc24/gradle-avro-plugin#123]
I was wondering if there is a way to generate protocols for all files even if they are named the same, but have different namespace ?

Example: 
```
(in src/main/avro directory) 
├── dir1
│   └── d_date_event.avdl
└── dir2
    └── d_date_event.avdl
         
```

The current behavior of `generateAvroProtocol` will just overwrite the first `d_date_event.avdl` file due to the way `.avpr` are stored in `generated-main-avro-avpr`.

**Comment by davidmc24** [comment]
Hmm. That's not the behavior I would expect. I'll verify, and if that is indeed the behavior, I'll fix it.

**Comment by davidmc24** [comment]
You are 100% correct of the current behavior, and present a good use case for why it should work differently.  Working on a fix.
