### ISSUE TITLE
Field-level ordering and deserialization

### ISSUE THREAD

**Issue by Schachte** [davidmc24/gradle-avro-plugin#124]
**Prerequisites**

* [x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [x] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [x] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this.
* [ x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

Wanting to get clarification on an issue we ran into with respect to auto-generated classes. 

I have schema A and I register it with root like fields like so:
```
{
  field1: "...",
  field2: "...",
  field3: "..."
}
```

fast-forward through time I change the schema and reorder the fields:
```
{
  field2: "...",
  field1: "...",
  field3: "...",
  field4: "..."
}
```

Now, this is deemed backward compatible from a schema evolution perspective and the updated schema is registered. However, deserialization with the new schema fails because the specific datum reader uses the newest auto-generated class. This class hardcodes field-level ordering indices in the pojo. 

I can bypass this failure by providing reader + writer schema, but this results in large performance degradation within our application. Curious on thoughts on this. 

Thanks!

**Comment by davidmc24** [comment]
Interesting problem.  Unfortunately, I think it's outside the scope of this plugin, as it would impact anything that uses the Apache Avro project's SpecificCompiler to generate Java classes.  I suggest taking this to the [Apache Avro](https://avro.apache.org/) mailing list and/or issue tracker.
