### ISSUE TITLE
Test doesn't actually verify what it claims to

### ISSUE THREAD

**Issue by bspeakmon** [davidmc24/gradle-avro-plugin#125]
https://github.com/davidmc24/gradle-avro-plugin/blob/852e371630fe7c6cc3d14a46b721fc5d38e9f14a/src/test/groovy/com/commercehub/gradle/plugin/avro/GenerateAvroProtocolTaskFunctionalSpec.groovy#L92

This test should check in the `v1` and `v2` directory instead of `v1` twice.

**Comment by davidmc24** [comment]
Thanks for the call-out.  Should be better now.
