### ISSUE TITLE
GenerateAvroJavaTask generates Java 11 compatible classes only

### ISSUE THREAD

**Issue by ilyamaris** [davidmc24/gradle-avro-plugin#126]
**Prerequisites**

* [x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [x] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [x] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this.
* [x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

**To Reproduce**

1. Project set up like this...
2. Source files like this...
3. Ran this task...

Please provide complete input files that reproduce the problem, not fragments.
When possible, please express this using `test-project`.

**Expected behavior**

**Environment (please complete the following information):**
 - Gradle Version [e.g. 5.6.1]
 - Apache Avro Version [e.g. 1.8.2]
 - Gradle-Avro Plugin Version [e.g. 0.17.0]
 - Java Version [e.g. 13.0.2]
 - OS: [e.g. Mac OS X Mojave, Windows 10, Ubuntu 16.04]

**Additional context**

**Comment by ilyamaris** [comment]
I'm using 0.18.0 version , and generating java classes from avro schema, tries to set sourceCompatibility to 8, but it fails to compile because classes are generated with var keywords.

**Comment by davidmc24** [comment]
Can you provide a test project that demonstrates this behavior?

I have automated test coverage for compatibility with Java 8, and it appears to be passing.

I attempted to reproduce the failure by taking the `test-project` in this repo, but was unable to.

For reference, the changes made were:
* downgrading to plugin version `0.18.0`
* downgrade to Avro version `1.9.1`
* downgrade to Gralde version `5.0`
* specify `sourceCompatibility=8`
* run using Java `1.8.0_265`

**Comment by ilyamaris** [comment]
Please close this bug, problem was with my local setup.
