### ISSUE TITLE
IntelliJ warning "Cannot access 'org.apache.avro.specific.SpecificRecord' which is a supertype of" since Avro 1.10.0

### ISSUE THREAD

**Issue by lathspell** [davidmc24/gradle-avro-plugin#130]
**Prerequisites**

* [x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [x] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [x] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this.
* [x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

After upgrading from Plugin version 0.20.0 / Avro 1.9.1 to Plugin verion 0.21.0 / Avro 1.10.0, IntelliJ starts giving mit red unterlinings with warnings: `Cannot access 'org.apache.avro.specific.SpecificRecord' which is a supertype of 'my.FooRecord'. Check your module classpath for missing or conflicting dependencies`. It does compile though!

The warnings are annoying but I cannot say who is to blame, IntelliJ, the plugin or the Avro library. I noticed that the `org/apache/avro/specific/` Folder is empty since Avro 1.10.0. Maybe the Plugin is supposed to create this `SpecificRecord` now?

 
**To Reproduce**

Create a project with the above versions and a simple .avcs file and open it with IntellIJ.

**Expected behavior**

No warnings in IntelliJ

**Environment (please complete the following information):**
 - Gradle Version 6.7
 - Apache Avro Version 1.10.0
 - Gradle-Avro Plugin Version 0.20.0
 - Java Version 11.0.8.hs-adpt
 - OS: Mac OS X 19.6.0

**Comment by davidmc24** [comment]
Thanks for the report.  I'll take a look.

**Comment by davidmc24** [comment]
The project in `test-project` of the plugin's repo appears to use the same plugin/avro versions as you called out.  I opened it in IntelliJ and initially didn't experience the warning you called out.

Based on the warning, my guess is that your project is using the Java Platform Module System (JPMS) to define a module, and there's something wrong in either your build file (not related to this plugin) or your module descriptor.  As far as I know the Apache Avro project does not yet publish module descriptors, which may complicate this usage.

**Comment by lathspell** [comment]
Thanks for the quick response!
I could reproduce it with `test-project`. Kind of at least as I this exact warning only comes in Kotlin files.
It appears if the dependency to "avro-tool" is removed! If you remove all test files which have a direct dependency on SpecificFoo class then the project will compile - but if you click on the generated source then you see IDE warnings, that e.g. `org.apache.avro.specific.SpecificRecord` cannot be found. It seems to have been moved from avro to avro-tools by upstream.

Could you please add the dependency to "avro-tools" to the README? 

P.S.: That README says "if you prefer to use the incubating plugins DSL" - I think that's the recommended way now.

**Comment by davidmc24** [comment]
Interesting. I'll look at it from that angle and update the documentation.

**Comment by lathspell** [comment]
Wait, that avro-tools dependency has way too much dependency to stuff I don't need, that can't be right.
Also I still don't understand why `$ jar tf ~/.gradle/caches/jars-8/c0148eb2fbd064182f0484dd117cd420/avro-1.10.0.jar | grep SpecificRecord.class`does show me a `org/apache/avro/specific/SpecificRecord.class` but if I open the Dependency in my or your project in IntelliJ the "org.apache.avro.specific" package seems to be empty.

**Comment by davidmc24** [comment]
Any chance your IntelliJ cached a bad copy of the jar?

**Comment by lathspell** [comment]
I deleted the ~/.m2/.../avro folder, invalidated all IntellIJ caches (again) and suddenly the warnings are gone. That's strange. I never hat IntelliJ doing such strange things.
You can probably closed this issue then!

**Comment by humamaboalraja** [comment]
Hi there. I'm re-opening this issue because I have recently encountered it in a multi-Kotlin/Gradle project setup.

---
Some context:
I have a module that generates a client from an Avro schema, and it's working fine, but when I try to access this dynamically generated client from my Kotlin client code, it says that:


- Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath: ... `classes where I'm using Avro's models`
- Cannot access 'org.apache.avro.specific.SpecificRecord `(or many others)`' which is a supertype of 'ExampleAvroModel'. Check your module classpath for missing or conflicting dependencies.
- Type argument is not within its bounds: should be subtype of 'SpecificRecordBase' - in case I was extending some type
- ...
---

Environment:
- Gradle 8.0
- Kotlin 1.8.0
- Java 17
- Apache Avro 1.11.1
- Gradle-Avro Plugin 0.20.0
- gradle.plugin.avro-base 1.6.0
- Apple M1 Max. Ventura 13.2.1
---

Example:

```kotlin
interface IKafkaConsumer<T : SpecificRecordBase>  {}

class UserResponseListener(
    private val userResponseMessageListener: userResponseMessageListener,
    private val userMessagingDataMapper: UsertMessagingDataMapper

) : IKafkaConsumer<MessageResponseAvroModel> {

    @KafkaListener(id = "\${placeholder}")
    override fun receive(@Payload messages: List<UserResponseAvroModel>) {
        messages.forEach {
                    when (it.profileStatus)  
                     //                ⬆ 
```

<p style="color: #ffaaae;">Cannot access 'org.apache.avro.generic.GenericContainer' which is a supertype of 'UserResponseAvroModel'. Check your module classpath for missing or conflicting dependencies</p>


---
