### ISSUE TITLE
Unable to use older versions of plugin

### ISSUE THREAD

**Issue by Rubyj** [davidmc24/gradle-avro-plugin#149]
@davidmc24 I am unable to use older versions of this repo in my kotlin projects. For example:

```
plugins {
    id("org.springframework.boot") version "2.2.10.RELEASE"
    id("io.spring.dependency-management") version "1.0.9.RELEASE"
    kotlin("jvm") version "1.4.21"
    kotlin("plugin.spring") version "1.4.21"
    // Generate Java classes from Avro schemas
    id("com.github.davidmc24.gradle.plugin.avro") version "0.16.0"
    // Linting
    id("org.jlleitschuh.gradle.ktlint") version "9.4.1"
    kotlin("kapt") version "1.4.21"
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    // Needed for Confluent
    maven(url = "https://packages.confluent.io/maven/")
    // Needed for springfox-swagger-ui:3.0.0-SNAPSHOT
    maven(url = "https://oss.jfrog.org/artifactory/oss-snapshot-local/")
    // exposed
    jcenter()
}
```

Results in the following error:

```
* What went wrong:
Plugin [id: 'com.github.davidmc24.gradle.plugin.avro', version: '0.16.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.davidmc24.gradle.plugin.avro:com.github.davidmc24.gradle.plugin.avro.gradle.plugin:0.16.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    BintrayJCenter
    maven(https://dl.bintray.com/gradle/gradle-plugins)
```

**Comment by paulbersch** [comment]
I'm unable to install `0.22.0` as well.

**Comment by paulbersch** [comment]
Looking at the changelog, it looks like this was an intentional change.
https://github.com/davidmc24/gradle-avro-plugin/blob/1.1.0/CHANGES.md#pre-10-versions

Is there any reason why older versions can't be hosted in Maven Central alongside the 1.X releases?

**Comment by Rubyj** [comment]
Unfortunately, we do not have the same luxury of upgrading as easily. We were using 0.16.0 and newer versions (0.21.0+ which is uploaded) dropped support for avro 1.9.1+ and our schema registry 5.4.0 is tied to avro 1.9.1

**Comment by davidmc24** [comment]
Maven Central has strict rules on what namespace it allows publishing under. I do not own the com.commercehub namespace and this project is no longer associated with CommerceHub, so it is impossible to publish the historical artifacts to Maven Central. If you need to continue using the historical artifacts, you are free to download them and host them privately wherever you would like.

**Comment by davidmc24** [comment]
I will look into why the previous versions aren't working for you.  They should work still, as JCenter is still resolving artifacts.  You should plan for what your approach will be when it stops, however.

**Comment by Rubyj** [comment]
I think JCenter is deprecating/browning out old deprecated artifacts including this one it kind of seems like

**Comment by davidmc24** [comment]
@Rubyj For you, I think the problem is just that you're using the wrong coordinates.  For the version you're trying to use, the declaration should be `id "com.commercehub.gradle.plugin.avro" version "0.16.0"`.  Note that the leading domain segment is different.

**Comment by davidmc24** [comment]
@paulbersch This works fine for me.  Can you provide a build file example that reproduces the problem, and the error message you're seeing?

```
plugins {
    id "com.commercehub.gradle.plugin.avro" version "0.22.0"
}


repositories {
    jcenter()
}
```

**Comment by Rubyj** [comment]
@davidmc24 that is actually the exact line we currently have in our project that no longer works all the time, which sparked this investigation. Supposedly, that is being "browned out" so it is intermittently now working. The brown out today has been "restored"

I no longer have the error unfortunately due to builds now passing.

From earlier today where you can see the brown out: https://status.bintray.com/incidents/4mzph0y8l6hk

It looks like however this may still be supported until 2022: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I think we can probably close this considering it's due to the repository's issues

**Comment by davidmc24** [comment]
@Rubyj  @paulbersch For both those examples, note that I have the following in `settings.gradle`:

```
pluginManagement {
    repositories {
        gradlePluginPortal()
        jcenter()
        maven {
            name "JCenter Gradle Plugins"
            url  "https://dl.bintray.com/gradle/gradle-plugins"
        }
    }
}
```

**Comment by davidmc24** [comment]
@Rubyj Gotcha.  Yep, nothing I can do about that.  Setting up a Nexus or Artifactory instance for your purposes, either caching JCenter or manually loaded with the appropriate artifacts should prevent further brownouts from impacting you.

**Comment by Rubyj** [comment]
Will do. Thanks for helping out @davidmc24

**Comment by paulbersch** [comment]
We must have been affected by the brownouts, too. Here's our settings.

settings.gradle
```
pluginManagement {
    repositories {
        gradlePluginPortal()
        jcenter()
        maven {
            url  "https://dl.bintray.com/gradle/gradle-plugins"
        }
    }
}
```

build.gradle

```
plugins {
    id 'java-library'
    id "com.github.johnrengelman.shadow" version "6.1.0"
    id 'com.commercehub.gradle.plugin.avro' version '0.22.0'
    id 'io.micronaut.library' version '1.1.0'
    id 'jacoco'
}
```

But using 1.0.0 works for us. Thanks for the additional context!

**Comment by davidmc24** [comment]
@Rubyj The hypothetical version 2.0 of this plugin will support arbitrary Avro versions. I just have a really hard time making time to work on it.  I might be able to get a stripped down alpha version available if you're interested.

**Comment by Rubyj** [comment]
@davidmc24 happy to test that alpha version in one of our apps in our development or staging environment if it would help. Right now we are using your newest version 1.1 with avro 1.9.1 even though it's not "supported" we aren't having any issues..

**Comment by davidmc24** [comment]
@Rubyj Good news.  Looks like there isn't a good reason for 1.9.1 to not be supported... so I'll be adding it as a supported version.  Probably some other versions as well.  The local-timestamp-millis logical type we use in a few tests isn't supported in 1.9.x, but it only require a tweak to the compatibility tests to work around that.  I should have the doc and test updates done sometime tonight.  No new release needed.

**Comment by Rubyj** [comment]
Awesome! Thanks @davidmc24 !! We did change some datetimes to timestamps with the new version but not big deal!

**Comment by davidmc24** [comment]
I think that with that version, time stamp will work, but not local time stamp.

**Comment by Rubyj** [comment]
hey @davidmc24 I am seeing the following error now when trying to download the latest version of your package 

```
* What went wrong:
Error resolving plugin [id: 'com.github.davidmc24.gradle.plugin.avro', version: '1.3.0']
> Could not resolve all dependencies for configuration 'detachedConfiguration6'.
   > Could not determine artifacts for com.github.davidmc24.gradle.plugin.avro:com.github.davidmc24.gradle.plugin.avro.gradle.plugin:1.3.0
      > Could not get resource 'https://plugins.gradle.org/m2/com/github/davidmc24/gradle/plugin/avro/com.github.davidmc24.gradle.plugin.avro.gradle.plugin/1.3.0/com.github.davidmc24.gradle.plugin.avro.gradle.plugin-1.3.0.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/com/github/davidmc24/gradle/plugin/avro/com.github.davidmc24.gradle.plugin.avro.gradle.plugin/1.3.0/com.github.davidmc24.gradle.plugin.avro.gradle.plugin-1.3.0.jar'. Received status code 502 from server: Bad Gateway
```

Is there an alternate to jcenter where we should get the plugin from?

**Comment by davidmc24** [comment]
That error makes it look like you're trying to resolve plugin version 1.3.0 from the Gradle Plugin Portal.  I discontinued publishing to the Gradle Plugin Portal back in 2017.  Versions 1.0.0+ are currently published to Maven Central.

Please see the documentation [here](https://github.com/davidmc24/gradle-avro-plugin#usage).
In particular, the `mavenCentral()` repository declaration in `settings.gradle`.

**Comment by Rubyj** [comment]
@davidmc24 We are using `mavenCentral()` unfortunately it also seems we are using the gradle plugin portal for some of our other dependencies. I wonder if there is a way to specify for this dependency in particular to use mavenCentral

**Comment by davidmc24** [comment]
Maybe change the order to put maven central first?  The issue here is that the plugin portal is broken right now, nothing related to this plugin. See https://status.gradle.com

**Comment by Rubyj** [comment]
yes! you read my mind @davidmc24 I was just trying that and it worked!

```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}
```
Thanks for the prompt responses!

**Comment by davidmc24** [comment]
Glad it's working for you!
