### ISSUE TITLE
Doesn't work under Gradle 7

### ISSUE THREAD

**Issue by robvadai** [davidmc24/gradle-avro-plugin#158]
**Prerequisites**

Using version 0.99.99
This is the latest one published to the Gradle plugin repo.

When I tried 1.2.0 it said cannot find version. Even when I use plugin management config.

**Describe the bug**

```
> Task :schemas:generateAvro FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':schemas:generateAvro' (type 'GenerateAvroJavaTask').
  - Type 'com.commercehub.gradle.plugin.avro.GenerateAvroJavaTask' property 'outputDir' is missing an input or output annotation.

    Reason: A property without annotation isn't considered during up-to-date checking.

    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.

    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

**To Reproduce**
```
 ./gradlew clean build -p schemas
```

or whatever is your project

Works without a problem under Gradle 6.9

**Comment by davidmc24** [comment]
The versions on the Gradle Plugin Portal are badly out of date. Please upgrade to version 1.0+ on Maven Central.

**Comment by robvadai** [comment]
Using Maven Central and latest version 1.2.0 works - thanks

**Comment by dssizh** [comment]
> Using Maven Central and latest version 1.2.0 works - thanks

Could you tell me where can I find this version?

**Comment by lilyevsky** [comment]
I cannot pull 1.2.0 from Maven Central. Was it removed? How should I get it now? What is the latest version I can get from some repository?

**Comment by jpag5416** [comment]
id 'com.commercehub.gradle.plugin.avro' version '1.2.0'
id 'com.github.davidmc24.gradle.plugin.avro' version '1.2.0'

@davidmc24 what is the difference between these 2 plugins . can we use any one?

**Comment by davidmc24** [comment]
@jpag5416 

The difference is documented here: https://github.com/davidmc24/gradle-avro-plugin/blob/master/CHANGES.md#pre-10-versions

Lineage-wise, both plugin IDs refer to the same plugin, and maintained/released by the same maintainer (me).

The `com.commercehub.gradle.plugin.avro` plugin ID was used earlier in the plugin's development (pre-1.0 versions) when it was somewhat sponsored by CommerceHub.  I switched to the davidmc24 ID when JCenter was deprecated, as Maven Central would not allow me to continue publishing to a namespace that I couldn't prove ownership of (as sponsorship by CommerceHub had already ended at that time).

Unless you have a specific legacy compatibility reason, always use the latest released version, which would be `id 'com.github.davidmc24.gradle.plugin.avro' version '1.7.1'` at the moment.
