### ISSUE TITLE
Problem to generate class with default type null

### ISSUE THREAD

**Issue by toonsms** [davidmc24/gradle-avro-plugin#177]
**Prerequisites**

* [x ] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [ x] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [ x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x ] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [ x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [x ] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this.
* [ ] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

**To Reproduce**

1. Project set up like this...
2. Source files like this...
3. Ran this task...

Please provide complete input files that reproduce the problem, not fragments.
When possible, please express this using `test-project`.

**Expected behavior**

**Environment (please complete the following information):**
 - Gradle Version [e.g. 5.6.1]
 - Apache Avro Version [e.g. 1.8.2]
 - Gradle-Avro Plugin Version [e.g. 0.17.0]
 - Java Version [e.g. 13.0.2]
 - OS: [e.g. Mac OS X Mojave, Windows 10, Ubuntu 16.04]

**Additional context**

I have the same problem on issue #111 and #112 and for me even the cache cleanning it wasn't enought. My schema looks like this:
(for reference, my version is 1.2.1 and my gradle wrapper is 6.8)
error:
![image](https://user-images.githubusercontent.com/91228568/134475624-cece4fe6-586a-40da-8f74-276f762fc175.png)

```json
{
    "type": "record",
    "name": "SomeEvent",
    "namespace": "someNameSpace",
    "fields": [
        {
            "name": "data",
            "type": {
                "type": "record",
                "name": "SomeEventData",
                "fields": [
                    {
                        "name": "Boleto",
                        "type": {
                            "type": "record",
                            "name": "Boleto",
                            "fields": [
                                {
                                    "name": "data_vencimento",
                                    "type": [
                                        "string"
                                    ],
                                    "default": null
                                }
                            ]
                        }
                    }
                ]
            }
        }
    ]
}
```

**Comment by davidmc24** [comment]
As already answered in your forum post (https://github.com/davidmc24/gradle-avro-plugin/discussions/176), your problem is that your schema is invalid.  If you run the Avro CLI command to compile the schema, you'll get the same error.  Please fix your schema.

```
java -jar downloads/avro-tools-1.10.2.jar compile schema input/SomeEvent.avsc output/
Input files to compile:
  input/SomeEvent.avsc
Exception in thread "main" org.apache.avro.AvroTypeException: Invalid default for field data_vencimento: null not a ["string"]
	at org.apache.avro.Schema.validateDefault(Schema.java:1576)
	at org.apache.avro.Schema.access$500(Schema.java:91)
	at org.apache.avro.Schema$Field.<init>(Schema.java:549)
	at org.apache.avro.Schema.parse(Schema.java:1683)
	at org.apache.avro.Schema.parse(Schema.java:1673)
	at org.apache.avro.Schema.parse(Schema.java:1673)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1430)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1393)
	at org.apache.avro.tool.SpecificCompilerTool.run(SpecificCompilerTool.java:154)
	at org.apache.avro.tool.Main.run(Main.java:67)
	at org.apache.avro.tool.Main.main(Main.java:56)
```

**Comment by toonsms** [comment]
Hi @davidmc24, I forgot to mention, I raised this question because the plugin of the Maven (https://mvnrepository.com/artifact/org.apache.avro/avro-maven-plugin/1.10.2) can set up the classes with this AVRO provided . I know it sounds silly, but I wanted to know if there was the possibility of building schemes like these also in the plugin
