### ISSUE TITLE
Use Avro 1.11.1 to generate from IDL

### ISSUE THREAD

**Issue by bob-chevalier** [davidmc24/gradle-avro-plugin#212]
**Describe the bug**

The latest version of Avro (1.11.1) adds support for new IDL syntax to specify nullable fields:
https://issues.apache.org/jira/browse/AVRO-3257

Since the latest version of the gradle-avro-plugin (1.4.0) uses Avro 1.11.0 internally, this syntax is not yet supported when converting .avdl files to .avpr.  It appears that the `master` branch of the gradle-avro-plugin does make use of Avro 1.11.1 so I'm hoping that a new release can be generated and published from the `master` branch.

**Comment by davidmc24** [comment]
Sure thing!  I was just waiting for clean CI run before releasing; and that passed, so I'll start the release now.

**Comment by davidmc24** [comment]
Release of 1.5.0 underway.  Should be synced to maven central within the day.

**Comment by bob-chevalier** [comment]
Thank you for the quick turnaround!

**Comment by davidmc24** [comment]
Released.
