### ISSUE TITLE
customEncode method not generated anymore

### ISSUE THREAD

**Issue by zaghdous** [davidmc24/gradle-avro-plugin#213]
Hi,

With the 0.17.0 version of the plugin, the generated code implements the method :
public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException

With the 0.20.0 version, this method is not implemented anymore. We need it to get a string representation of the key.
Do you plan to restore it in your next release ?
Thanks

**Comment by davidmc24** [comment]
The generated code is controlled by the version of Apache Avro used. If the latest version doesn't have the generated code that you want, please raise an issue with the Apache Avro project. Also, note that the versions you referenced are both badly out of date.

**Comment by zaghdous** [comment]
thanks
