### ISSUE TITLE
Avro "imports"/"extends" is not working

### ISSUE THREAD

**Issue by ronikurtberg** [davidmc24/gradle-avro-plugin#226]
Hi,

While trying to use Avro inheritance features, to include schema A within schema B, using `extends` and `includes`, the POJO's got created don't include the base class fields.

Use case:

base.avsc:
fields: [a1, ..., an]

child.avsc:
fields: [b1, ..., bn]
"includes": ["base.avsc"],
"extends": "base"

My expectation is the base class fields will be included within the child class, but that's not happening (checked the POJO created by the plugin for the child class).

Is that supported?

Thanks,

Roni

**Comment by davidmc24** [comment]
As far as I know, the Avro schema specification does not support inheritance. 

https://avro.apache.org/docs/1.10.2/spec.html#schema_record

This plugin only supports capabilities provided by the Avro SpecificCompiler library provided by the Apache Avro project. So, to answer your question, no, I don't believe this is supported. You are welcome to add such support in your own fork if you wish.

**Comment by ronikurtberg** [comment]
Thanks for the reply.
