### ISSUE TITLE
Cannot access 'org.apache.avro.specific.SpecificRecord' which is a supertype of...

### ISSUE THREAD

**Issue by humamaboalraja** [davidmc24/gradle-avro-plugin#227]
Hi there. I'm re-opening this issue because I have recently encountered it in a multi-Kotlin/Gradle project setup.

---
Some context:
I have a module that generates a client from an Avro schema, and it's working fine, but when I try to access this dynamically generated client from my Kotlin client code, it says that:

- Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath: ... `classes where I'm using Avro's models`
- Cannot access 'org.apache.avro.specific.SpecificRecord `(or many others)`' which is a supertype of 'ExampleAvroModel'. Check your module classpath for missing or conflicting dependencies.
- Type argument is not within its bounds: should be subtype of 'SpecificRecordBase' - in case I was extending some type
- ...
---

Environment:
- Gradle 8.0
- Kotlin 1.8.0
- Java 17
- Apache Avro 1.11.1
- Gradle-Avro Plugin 0.20.0
- gradle.plugin.avro-base 1.6.0
- Apple M1 Max. Ventura 13.2.1
---

Example:

```kotlin
interface IKafkaConsumer<T : SpecificRecordBase>  {}

class UserResponseListener(
    private val userResponseMessageListener: userResponseMessageListener,
    private val userMessagingDataMapper: UsertMessagingDataMapper

) : IKafkaConsumer<MessageResponseAvroModel> {

    @KafkaListener(id = "\${placeholder}")
    override fun receive(@Payload messages: List<UserResponseAvroModel>) {
        messages.forEach {
                    when (it.profileStatus)  
                     //                ⬆ 
```

<p style="color: #ffaaae;">Cannot access 'org.apache.avro.generic.GenericContainer' which is a supertype of 'UserResponseAvroModel'. Check your module classpath for missing or conflicting dependencies</p>

---

**Comment by davidmc24** [comment]
I suspect that your issues aren't really to do with the plugin, but rather likely dependency configuration or something Kotlin specific. To check whether it's actually the plugin do the following:

- Remove the plugin from your project
- Generate Java source files from your Avro files using the Apache Avro Tools command line utilities
- Put the generated source files under src/main/java or the equivalent in the project where you had been using the plugin
- Run the build

If you still get the problem, it's not the plugin. If it works fine, then it's probably the plugin.

Further explanation of how to use Apache Avro Tools can be found here: https://www.michael-noll.com/blog/2013/03/17/reading-and-writing-avro-files-from-the-command-line/

**Comment by davidmc24** [comment]
This project is now end-of-life (donated to the Apache Avro project).
