### ISSUE TITLE
Super Record's SCHEMA$ variable is not getting updated when subclass variable is changing type

### ISSUE THREAD

**Issue by 869kartik** [davidmc24/gradle-avro-plugin#232]
**Prerequisites**

* [x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases)) Yes
* [x] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md)) Yes
* [x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))Yes
* [x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md)) Yes
* [x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted? Yes
* [x] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this. Yes
* [x] Did you perform a cursory search?
Yes
For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

I created the two avro record. 
Super Class containing subclass
Subclass has a variable called stepId

Initially I defined StepId as string..pushed the changes to repo. Then I changed the stepId to Int.. 
Now the generated superclass has the entire schema variable as json. In that it still shows the stepid as String.
Only when I change something in superclass (i.e. doc or something) the schema variable is showing stepId as Int.

**To Reproduce**
Create two avro record.
Super Class containing subclass
Subclass has a variable called stepId
Initially I defined StepId as string..pushed the changes to repo. Then I changed the stepId to Int.. 
Super class will still have the stepId as String in the generated java class in the SCHEMA$ variable

1. Project set up like this...
2. Source files like this...
3. Ran this task...

Please provide complete input files that reproduce the problem, not fragments.
When possible, please express this using `test-project`.

**Expected behavior**

**Environment (please complete the following information):**
 - Gradle Version [e.g. 5.6.1]
 - Apache Avro Version [e.g. 1.8.2]
 - Gradle-Avro Plugin Version [e.g. 0.17.0]
 - Java Version [e.g. 13.0.2]
 - OS: [e.g. Mac OS X Mojave, Windows 10, Ubuntu 16.04]

**Additional context**

**Comment by davidmc24** [comment]
PRs welcome to fix this. In the meantime, a clean build should work around it.

**Comment by davidmc24** [comment]
This project is now end-of-life (donated to the Apache Avro project).
