### ISSUE TITLE
when using optional getters generated code has invalid javadoc

### ISSUE THREAD

**Issue by SingingBush** [davidmc24/gradle-avro-plugin#234]
I'm using Avro schema that has nullable list `union{null, array<ApplicableItem>} applicable_items = null;` and decided to configure the plugin to use _Optional_ fields:

```
tasks.register("generate", GenerateAvroJavaTask) {
    dependsOn generateSchema
    source file("../dist")
    include("**/*.avsc")
    createOptionalGetters = true
    optionalGettersForNullableFieldsOnly = true
    outputDir = file("build/generated/java")
}
```

On doing so I see a load of warnings in build log due to `<` characters in the javadoc:

```
warning: invalid input: '<'
* Gets the value of the 'applicable_items' field as an Optional&lt;java.util.List<chargebee.items.ApplicableItem>&gt;.
```

perhaps this relates to `'org.apache.avro:avro:1.11.1'` itself.

**Comment by davidmc24** [comment]
This almost certainly has to do with a change in either Avro version or Java tool version. The Avro Gradle plugin doesn't do any of the direct file generation. It delegates all of that to the Avro library. Try it with the Avro CLI tool, see if you get the same result, and if so, submit a ticket with the Apache Avro project.

**Comment by SingingBush** [comment]
ok thanks for confirming. I've created a bug in the Avro Jira https://issues.apache.org/jira/browse/AVRO-3788

**Comment by davidmc24** [comment]
This project is now end-of-life (donated to the Apache Avro project).
