### ISSUE TITLE
StackOverflowError when mixing jar files with AVDL files  and regular AVDL files 

### ISSUE THREAD

**Issue by perf-coder** [davidmc24/gradle-avro-plugin#240]
**Prerequisites**

* [ x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [ ] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [ x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [ x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [ x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [ x] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this.
* [ x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**
We will get Avro IDL files in a jar file. Using `zipTree` to add those IDL files to the `GenerateAvroProtocolTask` works fine.
When I try to have IDL files in the default location and merge them with the files in the jar file I get a `stackOverflowError`.

**To Reproduce**
Tested with JDK 17 and 21. Gradle version 8.4. Mac OS X 14

Added this to my local build file:
`tasks.withType<GenerateAvroProtocolTask> {  

    if (this.name.equals("generateAvroProtocol")) {   
        var files = source  
        var tmp = files.plus(zipTree("src/main/resources/definitions.jar"))  
        source(tmp)  
    }   
}  `

Have a jar file with some IDL files somewhere (`src/main/resources` above)
Have a IDL file in `src/main/avro`  

Run `gw generateAvroProtocol`  
Error is : `java.lang.StackOverflowError (no error message)`. 

The top part of the stack trace:  
` java.lang.StackOverflowError
com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2059)
com.google.common.cache.LocalCache.get(LocalCache.java:3966)
com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
org.gradle.api.tasks.util.internal.CachingPatternSpecFactory.createSpec(CachingPatternSpecFactory.java:49)
org.gradle.api.tasks.util.internal.PatternSpecFactory.createIncludeSpec(PatternSpecFactory.java:65)
org.gradle.api.tasks.util.internal.PatternSpecFactory.createSpec(PatternSpecFactory.java:58)
org.gradle.api.tasks.util.PatternSet.getAsSpec(PatternSet.java:165)
org.gradle.api.tasks.util.internal.IntersectionPatternSet.getAsSpec(IntersectionPatternSet.java:40)
org.gradle.api.tasks.util.internal.IntersectionPatternSet.getAsSpec(IntersectionPatternSet.java:40)
org.gradle.api.tasks.util.internal.IntersectionPatternSet.getAsSpec(IntersectionPatternSet.java:40)
`
And so on.

**Expected behavior**

Appropriate Avro schema files created. 

**Environment (please complete the following information):**
 - Gradle Version [e.g. 8.4]
 - Apache Avro Version [1.11.3]
 - Gradle-Avro Plugin Version [1.9.1]
 - Java Version [17]
 - OS: [Mac OS X 10.14

NOTE: change the file extension to `jar` since it actually is a jar file.

[definitions.gz](https://github.com/davidmc24/gradle-avro-plugin/files/13459158/definitions.gz)

IDL file in the avro directory: 
NOTE: change file extension to `avdl` since that's what it really is
[si.txt](https://github.com/davidmc24/gradle-avro-plugin/files/13459184/si.txt)

Workaround is not to mix jar imported files with regular files.

**Comment by davidmc24** [comment]
This project is now end-of-life (donated to the Apache Avro project).
