### ISSUE TITLE
 Task ':compileTestKotlin' uses this output of task ':generateTestAvroJava' without declaring an explicit or implicit dependency.

### ISSUE THREAD

**Issue by MV-GH** [davidmc24/gradle-avro-plugin#241]
**Prerequisites**

* [x] Are you running the latest version of the plugin? (Check [releases](https://github.com/davidmc24/gradle-avro-plugin/releases))
* [ ] Are you running a supported version of Gradle? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Apache Avro? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Are you running a supported version of Java? (Check the [README](https://github.com/davidmc24/gradle-avro-plugin/blob/master/README.md))
* [x] Did you check to see if an [issue](https://github.com/davidmc24/gradle-avro-plugin/issues) has already been submitted?
* [x] Are you reporting to the correct repository?  If your schema doesn't work with the Apache Avro CLI tool either, it's not a problem with this plugin.  Running your file through the `CLIComparisonTest` in the sample project under the `test-project` directory can help diagnose this.
* [x] Did you perform a cursory search?

For more information, see the [CONTRIBUTING](https://github.com/davidmc24/gradle-avro-plugin/blob/master/CONTRIBUTING.md) guide.

**Describe the bug**

Using gradle 8.5, I get this error when I added unit tests to my app, It worked fine before that.
```
 Task ':compileTestKotlin' uses this output of task ':generateTestAvroJava' without declaring an explicit or implicit dependency.
```

I fixed this by doing

```
tasks.compileTestKotlin {
    dependsOn(tasks.generateTestAvroJava)
}
```

**To Reproduce**

* Add this plugin
* works
* Add unit test
* no longer works

**Expected behavior**

**Environment (please complete the following information):**
 - Gradle Version [8.5]
 - Gradle-Avro Plugin Version ["1.9.1"
 - Java Version [e.g. 17]

**Additional context**

This should probably be fixed here

**Comment by davidmc24** [comment]
This project is now end-of-life (donated to the Apache Avro project).
