### ISSUE TITLE
0.17.0 fails to compile valid IDL

### ISSUE THREAD

**Issue by damianryan** [davidmc24/gradle-avro-plugin#83]
Plugin 0.17.0 fails to compile IDL where a record field that is a union of null and an enum has a default value declared.
 
Plugin version: 0.17.0
Avro version: 1.9.1
Gradle version: 5.5.1
Java version: 1.8.0u221
OS: Windows 10
 
Steps to reproduce:
 
Attempt to compile the following IDL:
```
@namespace("com.foo.bar")
protocol MyProtocol {
  enum MyEnum { FOO, BAR }
  record MyRecord {
    union { null, MyEnum } myField = "FOO";
  }
}
```
 
Expected:
 
IDL compiles
 
Actual:
```
Task :generateAvroProtocol FAILED
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':generateAvroProtocol'.
Invalid default for field myField: "FOO" not a ["null",{"type":"enum","name":"MyEnum","namespace":"com.foo.bar","symbols":["FOO","BAR"]}]
```

**Comment by damianryan** [comment]
Hi David

I came back to this some just recently and discovered the cause of the issue.

From avro 1.9.0 onwards the treatment of default values for unions changed - whereas before the default value could be any of the types in the union, it seems now that the default value can only be of the first type declared in the union.

Changing my original example to:

`@namespace("com.foo.bar")
protocol MyProtocol {
  enum MyEnum { FOO, BAR }
  record MyRecord {
    union { MyEnum, null } myField = "FOO"; // swapped order of types in union
  }
}`

works with avro 1.8.2 and avro 1.9.1 using both version 1.16.0 and 1.17.0 of the plugin.

**Comment by davidmc24** [comment]
Thanks for the

**Comment by davidmc24** [comment]
@damianryan Thanks for the update.  That sounds like a really surprising and annoying behavior in Avro, regardless of whether they consider it a feature or a bug.  Regardless, am I correct in understanding that there is nothing that needs to be changed in this plugin to better support this behavior?

**Comment by damianryan** [comment]
@davidmc24 Yes, David, nothing in the plugin needs changing. As long as IDL files are written such that a default value for a union has its type declared first in the union, the code will compile under the most recent version of the plugin, as well as 0.16.0 with both avro 1.8.2 and 1.9.x.
