### ISSUE TITLE
Determine the release process for the next major version

### ISSUE THREAD

**Issue by davidmc24** [davidmc24/gradle-avro-plugin#91]
This project is no longer a CommerceHub OSS project.  As such, it probably doesn't make sense to publish to the CommerceHub OSS bintray project any more.

Consider:

1. Whether to publish to Bintray/JCenter, and if so, where
2. Whether to publish to Maven Central
3. Whether to publish to the Gradle Plugin Portal
4. What artifact coordinates to use
5. What plugin ID to use
6. Whether to change the class package structure

Make sure to update RELEASING.md with the results.

**Comment by pdebuitlear** [comment]
@davidmc24 Just wondering if you've had any further thoughts on publishing to a repo?

**Comment by davidmc24** [comment]
All releases to date are still published to JCenter. 

I’m going to delay changing coordinates until the next major version. At that point, my plan is to publish to both JCenter and Maven Central, but not the Gradle Plugin Portal, as they still don’t have easy to access download statistics.

**Comment by davidmc24** [comment]
Until/unless download stats are provided by the Gradle Plugin Portal, I will definitely **not** be publishing new versions of this plugin to the Gradle Plugin portal.  If you're interested in using the Gradle Plugin Portal, I suggest that you encourage Gradle to work on https://github.com/gradle/plugin-portal-requests/issues/2 (which I first requested back in 2015 under https://discuss.gradle.org/t/plugin-portal-download-statistics/11609).

**Comment by davidmc24** [comment]
Well... I hadn't expected to work on this ticket so soon, but the migration is done.  Due to #133, the plugin is now published to Maven Central with a different artifact/plugin/package namespace.
