### ISSUE TITLE
Add config param for customConversions

### ISSUE THREAD

**Issue by ppussar** [davidmc24/gradle-avro-plugin#92]
A configuration parameter for adding custom conversions would be nice, similar as it is already available in the [avro-maven-plugin](https://github.com/apache/avro/blob/62f3c26e2c303df0a208590041bcf20590fce62d/lang/java/maven-plugin/src/main/java/org/apache/avro/mojo/SchemaMojo.java#L90)

**Comment by davidmc24** [comment]
Thanks for the call-out.  Yes, this feature sounds like it makes sense to add.

**Comment by masoncj** [comment]
@davidmc24 I also need this imminently for UUID support.  (I'm writing lots of IDL with UUIDs as ids, and would like the generated Java to use the native `java.lang.UUID` type.)  Would you be interested in a PR here or do you have something already?

**Comment by davidmc24** [comment]
@masoncj I think I’ve got it mostly (maybe fully?) working in the customConversions branch, but it may be a few days until I have time to get back to it. If you have the ability, I’d appreciate if you could see if it looks to meet your needs.

**Comment by masoncj** [comment]
Thanks @davidmc24! I was able to get this to work, but it was definitely a trick to do so.

I locally installed your `customConversions` branch of this plugin, as well as apache/avro#655 (which fixes the issue with `@logicalType()` not being recognized on `string`). I had to work around the fact that `SpecificCompiler.DateTimeLogicalTypeImplementation` seems to have gone away or moved in the most recent Avro version(s).  

I also had to create a small shim factory class:

```
package com.commercehub.gradle.plugin.avro; // Temporarily here
import org.apache.avro.*;
public class UUIDLogicalTypeFactory implements LogicalTypes.LogicalTypeFactory {
    @Override
    public LogicalType fromSchema(Schema schema) {
        return LogicalTypes.uuid();
    }
}
```
(Ultimately, I'm not sure where this factory class should go so that it's visible to both compiler and client code.  Is there a way we could ease this for types like UUID that have builtin LogicalTypes?)

Then, I'm able to activate this in my `build.gradle`:
```
avro {
    logicalTypeFactory("uuid", UUIDLogicalTypeFactory)
    customConversion(org.apache.avro.Conversions.UUIDConversion)
}
```

With the following Schema:
```
protocol Test {
  record EventRecord {
    @logicalType("uuid") string eventId;
    timestamp_ms createdAt;
  }
}
```

I'm able to write this test (in Kotlin):
```
class TestAvroUUID {
    @Test
    fun testUuidRoundtrip() {
        val uuid = UUID.randomUUID()
        val now = Instant.now()

        val event = EventRecord.newBuilder()
            .setEventId(uuid)
            .setCreatedAt(now)
        val buffer = event.build().toByteBuffer()

        val outEvent = EventRecord.fromByteBuffer(buffer)
        assertEquals(now, outEvent.createdAt)
        assertEquals(uuid, outEvent.eventId)
    }
}
```

I document this here because I spent hours trying to figure out how to handle UUID fields which seem like a very simple thing to want to do!

LMK if I can help with documentation (maybe I could add the above example in the README?) or if you have ideas about how to handle the UUID LogicalType?

**Comment by davidmc24** [comment]
I’m sorry to hear that it sounds like they’ve broken compatibility yet again. For release plugin versions, I’ll wait until that’s in a release of Avro to deal with it.

That they have a pull request to fix the string logical type bug is encouraging, though. 

My expectation is that if you’re using this feature, it will be necessary to provide a LogicalTypeFactory, Conversion and (usually) a LogicalType implementation, configure the plugin to tell it about the LogicalTypeFactory and Conversion, and make the classes above available on both the build script classpath and compile classpath.

Probably the best practice would be to set your custom conversions/logical types up as a separate Gradle projects and publish them as a jar. Then, you could reference the jar as a dependency as needed.

I don’t think it’s likely to be a common thing that there are built-in LogicalTypes and Conversions for things without a LogicalTypeFactory. At least, not enough to justify a special feature from this plugin. If there are a few types like that, it might be worth requesting that the upstream Apache Avro project just provide a LogicalTypeFactory. 

Are there many types that Avro ships with but don’t work without custom registration?  If so, I could probably be convinced to add a “enableBuiltinConversions” flag or something like that. That sounds like a usability miss from the upstream if they don’t either enable them by default or have an easy way to do so.

**Comment by davidmc24** [comment]
Partially answering my own question...

It looks to me like [`LogicalTypes`](https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java) currently references 9 built-in logical types.

It looks to me like [`SpecificCompiler`](https://github.com/apache/avro/blob/master/lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java) currently has built-in support for registering conversions for 5 of them in [`addLogicalTypeConversions()`](https://github.com/apache/avro/blob/master/lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java#L98) and another in [`initializeSpecificData()`](https://github.com/apache/avro/blob/master/lang/java/compiler/src/main/java/org/apache/avro/compiler/specific/SpecificCompiler.java#L353).

That leaves `uuid`, `local-timestamp-millis`, and `local-timestamp-micros` as the ones left out.

Maybe I'm misreading, but based on the code in [`LogicalTypes.fromSchemaImpl(Schema, boolean)`](https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/LogicalTypes.java#L66), I wouldn't have expected a special `LogicalTypeFactory` to be needed for UUID support as long as you used name "uuid", as it looks for the built-in names before ever consulting the map of registered logical type factories.
