### ISSUE TITLE
Add support for createAllArgsConstructor

### ISSUE THREAD

**Issue by davidmc24** [davidmc24/gradle-avro-plugin#93]
This configuration appears to have been added to SpecificCompiler in Avro 1.8.1.

**Comment by davidmc24** [comment]
No setter, so not really an option.  Rather, https://issues.apache.org/jira/browse/AVRO-1642 appears to indicate that it automatically omits the all-args constructor in some cases (if there are too many fields).

**Comment by marccerrato** [comment]
Hey! I was wondering if there's a way to avoid the creation of the `AllArgsConstructor`.
We want to enforce using the builder so that adding a new field to the schema wouldn't break the constructor.

**Comment by davidmc24** [comment]
As far as I can tell, Apache Aveo doesn't expose a simple configuration option for this.

Two options for you: either submit a feature request to the Apache Aveo project, or use a custom template.
