### ISSUE TITLE
Support Task Configuration Avoidance

### ISSUE THREAD

**Issue by dcabasson** [davidmc24/gradle-avro-plugin#97]
See https://docs.gradle.org/current/userguide/task_configuration_avoidance.html for context.

Currently the `AvroPlugin` is using tasks.create which should be changed to tasks.register as per the document above to leverage the gradle feature for task configuration avoidance.

**Comment by davidmc24** [comment]
Thanks for the suggestion. Makes sense; pull requests welcome.

**Comment by davidmc24** [comment]
@dcabasson I have what I hope is a functional implementation in master now, derived from your pull request.  Please take a look and see if it seems to meet your needs.
