### ISSUE TITLE
Reference schemas are not getting preserved , Getting completely embedded in the avsc from avdl

### ISSUE THREAD

**Issue by karansinghkjs346** [davidmc24/gradle-avro-plugin#99]
Hi I am having avdl from which i am trying to create the avsc but while creating the dependencies are getting completely embedded, they are not getting cross-referenced 

It makes union types out of the parents, that includes the definitions of the embedded types within

For example 

{
    "type": "record",
    "name": "EMPLOYEE",
    "namespace": "",
    "doc": "EMPLOYEE is a person that works for the VIDEO STORE",
    "fields": [
        {
            "name": "rentalrecord",
            "doc": "A rental record is a record on every rental",
            "type": "RENTALRECORD"
        },
        {
            "name": "hire_date",
            "doc": "Employee date of hire",
            "type": "int"
        }
    ]
}

Something like this I want to have Rental record as a reference in the other schema not getting embedded in that completely

**Comment by davidmc24** [comment]
If I'm understanding correctly, you have an AVDL file, and you're trying to use `GenerateAvroProtocolTask` and `GenerateAvroSchemaTask` to generate avsc Avro schema files from it, as documented in [Generating schema files](https://github.com/davidmc24/gradle-avro-plugin#generating-schema-files)?

Unfortunately, the upstream library, [avro-compiler](https://github.com/apache/avro/tree/master/lang/java/compiler), doesn't have any capability for writing separate files for each type in a schema.  The mechanism currently being used is [`Schema.toString(boolean)`](https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/Schema.html#toString(boolean)).

If the upstream library adds such a capability, I would be happy to make it usable in this plugin.  If desired, you can contact the upstream project, [Apache Avro](https://avro.apache.org/) to request this feature.
